# Ex 1.6 Intro to NLP and Network Analysis

### 1. Install libraries

In [18]:
# Spacy doesn't work in Python 3.13 so I've had to make a new virtual environment
# running Python 3.11 and installed spacy there.

In [8]:
!conda install pandas -y

Jupyter detected...
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/nlp_env

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bottleneck-1.4.2           |  py311h9b7fc35_0         153 KB
    numexpr-2.11.0             |  py311h20bc273_0         208 KB
    numpy-2.0.1                |  py311h13f252e_1          12 KB
    numpy-base-2.0.1           |  py311ha745260_1         8.4 MB
    pandas-2.3.1               |  py311hebe84f7_0        15.0 MB
    pytz-2025.2                |  py311hecd8cb5_0         239 KB
    ------------------------------------------------------------
                                           Total:        24.0 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/osx-64::blas-1.0-openblas
  bottleneck         pkgs/main/osx-64::bottleneck-1.4.2-py311h9b7fc35_0
  numexpr            pkgs/main/osx-64::numexpr-2.11.0-py311h20bc273_0
  numpy-base         pkgs/main/osx-64::numpy-base-2.0.1-py311ha745260_1
  pandas             pkgs/main/osx-64::pandas-2.3.1-py311hebe84f7_0
  python-tzdata      pkgs/main/noarch::python-tzdata-2025.2-pyhd3eb1b0_0
  pytz               pkgs/main/osx-64::pytz-2025.2-py311hecd8cb5_0

The following packages will be REMOVED:

  libblas-3.11.0-4_he492b99_openblas
  libcblas-3.11.0-4_h9b27e0a_openblas
  liblapack-3.11.0-4_h859234e_openblas

The following packages will be SUPERSEDED by a higher-priority channel:

  numpy              conda-forge::numpy-2.3.5-py311hf157cb~ --> pkgs/main::numpy-2.0.1-py311h13f252e_1



Downloading and Extracting Packages:
pandas-2.3.1         | 15.0 MB   |                                       |   0%
numpy-base-2.0.1     | 8.4 MB    |                                       |   0%

pytz-2025.2          | 239 KB    |                                       |   0%


numexpr-2.11.0       | 208 KB    |                                       |   0%



bottleneck-1.4.2     | 153 KB    |                                       |   0%




numpy-2.0.1          | 12 KB     |                                       |   0%


numexpr-2.11.0       | 208 KB    | ##8                                   |   8%
numpy-base-2.0.1     | 8.4 MB    |                                       |   0%

pytz-2025.2          | 239 KB    | ##4                                   |   7%


numexpr-2.11.0       | 208 KB    | ##################################### | 100%



pandas-2.3.1         | 15.0 MB   |                                       |   0%
numpy-base-2.0.1     | 8.4 MB    | #                                     |   3%

pytz-2025.2          | 239 KB    | ##################################### | 100%



bottleneck-1.4.2     | 153 KB    | ##################################### | 100%




numpy-2.0.1          | 12 KB     | ##################################### | 100%




numpy-2.0.1          | 12 KB     | ##################################### | 100%
numpy-base-2.0.1     | 8.4 MB    | ###9                                  |  11%


numexpr-2.11.0       | 208 KB    | ##################################### | 100%


pandas-2.3.1         | 15.0 MB   | 3                                     |   1%




numpy-2.0.1          | 12 KB     | ##################################### | 100%
numpy-base-2.0.1     | 8.4 MB    | #####3                                |  14%



bottleneck-1.4.2     | 153 KB    | ##################################### | 100%



pandas-2.3.1         | 15.0 MB   | #2                                    |   3%
pandas-2.3.1         | 15.0 MB   | ##6                                   |   7%
pandas-2.3.1         | 15.0 MB   | ####3                                 |  12%
numpy-base-2.0.1     | 8.4 MB    | ################2                     |  44%
pandas-2.3.1         | 15.0 MB   | #####2                                |  14%
pandas-2.3.1         | 15.0 MB   | ######1                               |  17%
pandas-2.3.1         | 15.0 MB   | #######                               |  19%
pandas-2.3.1         | 15.0 MB   | #######8                              |  21%
pandas-2.3.1         | 15.0 MB   | ########7                             |  24%
pandas-2.3.1         | 15.0 MB   | #########5                            |  26%
numpy-base-2.0.1     | 8.4 MB    | ###################################4  |  96%

pytz-2025.2          | 239 KB    | ##################################### | 100%

pandas-2.3.1         | 15.0 MB   | ##########3                           |  28%
pandas-2.3.1         | 15.0 MB   | ##################################### | 100%
















Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [10]:
!conda install networkx -y

Jupyter detected...
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/nlp_env

  added / updated specs:
    - networkx


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    networkx-3.4.2             |  py311hecd8cb5_0         3.1 MB
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

  networkx           pkgs/main/osx-64::networkx-3.4.2-py311hecd8cb5_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [12]:
!conda install matplotlib -y

Jupyter detected...
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/nlp_env

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    contourpy-1.3.1            |  py311h1962661_0         270 KB
    fonttools-4.55.3           |  py311h46256e1_0         2.9 MB
    kiwisolver-1.4.8           |  py311h6d0c2b6_0          60 KB
    matplotlib-3.10.0          |  py311hecd8cb5_0           8 KB
    matplotlib-base-3.10.0     |  py311h919b35b_0         8.3 MB
    pillow-11.3.0              |  py311h25d8182_0         968 KB
    pyparsing-3.2.0            |  py311hecd8cb5_0         480 KB
    unicodedata2-15.1.0        |  py311h46256e1_1         517 KB
    ------------------------------------------------------------
                                           Total:        13.4 MB

The following NEW packages will be INSTALLED:

  aom                pkgs/main/osx-64::aom-3.6.0-hcec6c5f_0
  cairo              pkgs/main/osx-64::cairo-1.16.0-h08824b9_6
  contourpy          pkgs/main/osx-64::contourpy-1.3.1-py311h1962661_0
  cycler             pkgs/main/noarch::cycler-0.11.0-pyhd3eb1b0_0
  dav1d              pkgs/main/osx-64::dav1d-1.2.1-h6c40b1e_0
  fontconfig         pkgs/main/osx-64::fontconfig-2.14.1-h269ac6a_3
  fonttools          pkgs/main/osx-64::fonttools-4.55.3-py311h46256e1_0
  freetype           pkgs/main/osx-64::freetype-2.13.3-h02243ff_0
  fribidi            pkgs/main/osx-64::fribidi-1.0.10-haf1e3a3_0
  gettext            pkgs/main/osx-64::gettext-0.21.0-h4e8c18a_2
  graphite2          pkgs/main/osx-64::graphite2-1.3.14-he9d5cce_1
  harfbuzz           pkgs/main/osx-64::harfbuzz-10.2.0-h060d35a_1
  icu                pkgs/main/osx-64::icu-73.1-hcec6c5f_0
  jpeg               pkgs/main/osx-64::jpeg-9e-h46256e1_3
  kiwisolver         pkgs/main/osx-64::kiwisolver-1.4.8-py311h6d0c2b6_0
  lcms2              pkgs/main/osx-64::lcms2-2.16-h31d93a5_1
  lerc               pkgs/main/osx-64::lerc-4.0.0-h6d0c2b6_0
  libavif            pkgs/main/osx-64::libavif-1.1.1-h46256e1_0
  libdeflate         pkgs/main/osx-64::libdeflate-1.22-h46256e1_0
  libglib            pkgs/main/osx-64::libglib-2.84.2-heb90364_0
  libiconv           pkgs/main/osx-64::libiconv-1.16-h6c40b1e_3
  libpng             pkgs/main/osx-64::libpng-1.6.39-h6c40b1e_0
  libtiff            pkgs/main/osx-64::libtiff-4.7.0-h2dfa3ea_0
  libwebp-base       pkgs/main/osx-64::libwebp-base-1.3.2-h46256e1_1
  libxml2            pkgs/main/osx-64::libxml2-2.13.8-h6070cd6_0
  lz4-c              pkgs/main/osx-64::lz4-c-1.9.4-hcec6c5f_1
  matplotlib         pkgs/main/osx-64::matplotlib-3.10.0-py311hecd8cb5_0
  matplotlib-base    pkgs/main/osx-64::matplotlib-base-3.10.0-py311h919b35b_0
  openjpeg           pkgs/main/osx-64::openjpeg-2.5.2-h2d09ccc_1
  pcre2              pkgs/main/osx-64::pcre2-10.42-h9b97e30_1
  pillow             pkgs/main/osx-64::pillow-11.3.0-py311h25d8182_0
  pixman             pkgs/main/osx-64::pixman-0.46.4-hb254d66_0
  pyparsing          pkgs/main/osx-64::pyparsing-3.2.0-py311hecd8cb5_0
  unicodedata2       pkgs/main/osx-64::unicodedata2-15.1.0-py311h46256e1_1
  zstd               pkgs/main/osx-64::zstd-1.5.6-h138b38a_0



Downloading and Extracting Packages:
matplotlib-base-3.10 | 8.3 MB    |                                       |   0%
fonttools-4.55.3     | 2.9 MB    |                                       |   0%

pillow-11.3.0        | 968 KB    |                                       |   0%


unicodedata2-15.1.0  | 517 KB    |                                       |   0%



pyparsing-3.2.0      | 480 KB    |                                       |   0%




contourpy-1.3.1      | 270 KB    |                                       |   0%





kiwisolver-1.4.8     | 60 KB     |                                       |   0%






matplotlib-base-3.10 | 8.3 MB    |                                       |   0%


unicodedata2-15.1.0  | 517 KB    | #1                                    |   3%



pyparsing-3.2.0      | 480 KB    | #2                                    |   3%

pillow-11.3.0        | 968 KB    | 6                                     |   2%
fonttools-4.55.3     | 2.9 MB    | 1                                     |   1%


unicodedata2-15.1.0  | 517 KB    | ######################8               |  62%



matplotlib-base-3.10 | 8.3 MB    | #                                     |   3%
fonttools-4.55.3     | 2.9 MB    | ##1                                   |   6%



pyparsing-3.2.0      | 480 KB    | ####################9                 |  57%


unicodedata2-15.1.0  | 517 KB    | ##################################3   |  93%

pillow-11.3.0        | 968 KB    | #8                                    |   5%


unicodedata2-15.1.0  | 517 KB    | ##################################### | 100%


unicodedata2-15.1.0  | 517 KB    | ##################################### | 100%



pyparsing-3.2.0      | 480 KB    | ##################################### | 100%
fonttools-4.55.3     | 2.9 MB    | #######                               |  19%

matplotlib-base-3.10 | 8.3 MB    | ####2                                 |  11%




contourpy-1.3.1      | 270 KB    | ##1                                   |   6%



pyparsing-3.2.0      | 480 KB    | ##################################### | 100%



pyparsing-3.2.0      | 480 KB    | ##################################### | 100%





kiwisolver-1.4.8     | 60 KB     | #########8                            |  27%





matplotlib-base-3.10 | 8.3 MB    | #####6                                |  15%
fonttools-4.55.3     | 2.9 MB    | ##########                            |  27%

pillow-11.3.0        | 968 KB    | ######7                               |  18%




contourpy-1.3.1      | 270 KB    | ##################################### | 100%





kiwisolver-1.4.8     | 60 KB     | ##################################### | 100%






matplotlib-3.10.0    | 8 KB      | ##################################### | 100%






matplotlib-base-3.10 | 8.3 MB    | ##########                            |  27%
fonttools-4.55.3     | 2.9 MB    | ##################6                   |  50%






matplotlib-3.10.0    | 8 KB      | ##################################### | 100%

pillow-11.3.0        | 968 KB    | ############2                         |  33%




contourpy-1.3.1      | 270 KB    | ##################################### | 100%




contourpy-1.3.1      | 270 KB    | ##################################### | 100%
fonttools-4.55.3     | 2.9 MB    | ########################3             |  66%

matplotlib-base-3.10 | 8.3 MB    | ############3                         |  34%
fonttools-4.55.3     | 2.9 MB    | #############################6        |  80%

matplotlib-base-3.10 | 8.3 MB    | ##############4                       |  39%
fonttools-4.55.3     | 2.9 MB    | ####################################7 |  99%

pillow-11.3.0        | 968 KB    | ########################4             |  66%
matplotlib-base-3.10 | 8.3 MB    | ################4                     |  44%

matplotlib-base-3.10 | 8.3 MB    | ##################4                   |  50%

pillow-11.3.0        | 968 KB    | ##################################8   |  94%

matplotlib-base-3.10 | 8.3 MB    | #########################7            |  70%

matplotlib-base-3.10 | 8.3 MB    | #################################2    |  90%





























Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [14]:
!conda install scipy -y

Jupyter detected...
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/nlp_env

  added / updated specs:
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.16.0               |  py311hcd1e4c7_0        23.7 MB
    ------------------------------------------------------------
                                           Total:        23.7 MB

The following NEW packages will be INSTALLED:

  scipy              pkgs/main/osx-64::scipy-1.16.0-py311hcd1e4c7_0

The following packages will be SUPERSEDED by a higher-priority channel:

  libgfortran        conda-forge::libgfortran-15.2.0-h7e5c~ --> pkgs/main::libgfortran-5.0.0-11_3_0_hecd8cb5_28
  libgfortran5       conda-forge::libgfortran5-15.2.0-hd16~ --> pkgs/main::libgfortran5-11.3.0-h9dfd629_28
  libopenblas        conda-forge::libopenblas-0.3.30-openm~ --> pkgs/main::libopenblas-0.3.29-h3f8574a_0



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

### 2. Import libraries

In [15]:
import pandas as pd
import numpy as np
import spacy
from spacy import displacy
import networkx as nx
import os
import matplotlib.pyplot as plt
import scipy
import re

In [20]:
print(spacy.__version__)

3.8.11

In [21]:
# Download English module

!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 7.7 MB/s  0:00:01 eta 0:00:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [22]:
# Load spacy English module

NER = spacy.load("en_core_web_sm")

### 3. Load text file

In [23]:
# Load the 20th century textfile

with open('key_events_20th_century.txt', 'r', errors='ignore') as file:
    data = file.read().replace('\n', '')

In [24]:
# Create dataframe of list of countries

df_countries = pd.read_csv(('countries_list_20th_century_1.5.csv'), index_col = False)

### 4. Wrangling steps

The same wrangling steps from Ex 1.5 will need to be reapplied to make sure the list of countries can be searched for.  This is to replace entries such as Korea, North with North Korea.

In [58]:
# Perform the same wrangling actions as in Ex 1.5:

# Remove spaces before and after country names

df_countries['country_name'] = df_countries['country_name'].str.strip()

In [59]:
# Some of the name are formatted in a way that won't allow them to be found in the text.
# Create a mapping of old names -> new names for the sake of counting them

replace_names = {
    'Korea, North': 'North Korea',
    'Korea, South': 'South Korea',
    "China, People's Republic of": 'China',
    'Bahamas, The': 'Bahamas',
    'Congo, Democratic Republic of the': 'Congo',
    'Congo, Republic of the': 'Congo',
    'Gambia, The':'Gambia',
    'Micronesia, Federated States of': 'Micronesia',
    'Vatican City (Holy See)': 'Vatican'}

# Apply the replacements
df_countries['country_name'] = df_countries['country_name'].replace(replace_names)

In [39]:
# Now add one space to the end of each country name.  This is for consistency, to stop words like 'Japanese' being counted as one mention 
# of Japan while the word 'French' would not count as one mention of 'France'.

# Delete this step now

#df_countries['country_name'] = df_countries['country_name'] + " "

In [60]:
df_countries.head(10)

          country_name
0          Afghanistan
1              Albania
2              Algeria
3              Andorra
4               Angola
5  Antigua and Barbuda
6            Argentina
7              Armenia
8            Australia
9              Austria

In [61]:
# Export df.countries to csv file

df_countries.to_csv('/Users/andymiller/20th-Century/list_of_countries_1.6.csv')

### 5. Create a NER object

In [62]:
article = NER(data)

In [63]:
# Visualize identified entities

displacy.render(article[273:20000], style = "ent", jupyter = True)

### 6. Split sentence entities from NER object

In [64]:
df_sentences = [] # empty shell to store results

# Loop through sentences, get entity list for each sentence
for sent in article.sents:
    entity_list = [ent.text for ent in sent.ents]
    df_sentences.append({"sentence": sent, "entities": entity_list})
    
df_sentences = pd.DataFrame(df_sentences)

In [45]:
df_sentences.head(10)

,sentence,entities
0,"(Jump, to, contentMain, menuSearchDonateCreate...","[Jump, 20th, Historic, the 20th century, links..."
1,"(languagesArticleTalkReadEditView, historyTool...","[Wikipedia, encyclopediaThe 20th century]"
2,"(The, World, Wars, sparked, tension, between, ...","[The World Wars, the Cold War, the Space Race,..."
3,"(These, advancements, have, played, a, signifi...","[the 21st century, today]"
4,"(Historic, events, in, the, 20th, century[edit...","[the 20th, Edwardian, 1914The, the 20th century]"
5,"(The, 1900s, saw, the, decade, herald, a, seri...","[The 1900s, the decade]"
6,"(1914, saw, the, completion, of, the, Panama, ...","[1914, the Panama Canal]"
7,"(The, Scramble, for, Africa, continued, in, th...","[Scramble, Africa, the 1900s]"
8,"(The, atrocities, in, the, Congo, Free, State,...",[the Congo Free State]
9,"(From, 1914, to, 1918, ,, the, First, World, W...","[1914 to 1918, the First World War]"

### 7. Filter the entities according to country list

In [53]:
df_countries.head()

   country_name
0  Afghanistan
1      Albania
2      Algeria
3      Andorra
4       Angola

In [65]:
# Function to filter out entities not of interest

def filter_entity(ent_list, df_countries):
    return [ent for ent in ent_list 
            if ent in list(df_countries['country_name'])]

In [67]:
# Check

filter_entity(["United States", "North Korea", "2", "banana"], df_countries)

['United States', 'North Korea']

In [68]:
df_sentences['country_entities'] = df_sentences['entities'].apply(lambda x: filter_entity(x, df_countries))

In [69]:
df_sentences['country_entities'].head(20)

0                    []
1                    []
2                    []
3                    []
4                    []
5                    []
6                    []
7                    []
8                    []
9                    []
10                   []
11                   []
12                   []
13     [France, Russia]
14    [Germany, Russia]
15            [Germany]
16            [Germany]
17                   []
18                   []
19                   []
Name: country_entities, dtype: object

In [70]:
# Filter out sentences that don't have any character entities

df_sentences_filtered = df_sentences[df_sentences['country_entities'].map(len) > 0]

In [71]:
df_sentences_filtered.head(20)

,sentence,entities,country_entities
13,"(After, a, period, of, diplomatic, and, milita...","[the July Crisis, the end of July 1914, the Br...","[France, Russia]"
14,"(The, Bolsheviks, negotiated, the, Treaty, of,...","[Bolsheviks, Germany, Russia]","[Germany, Russia]"
15,"(In, the, treaty, ,, Bolshevik, Russia, ceded,...","[Bolshevik Russia, Baltic, Germany, Kars Oblas...",[Germany]
16,"(It, also, recognized, the, independence, of, ...","[Germany, Allied, American]",[Germany]
21,"(Many, Germans, felt, these, reparations, were...","[Germans, Germany, Allied, Kaiser, Europe]",[Germany]
39,"(Germany, ,, 1933Fascism, first, appeared, in,...","[Germany, first, Italy, Benito Mussolini, 1922...","[Germany, Italy]"
40,"(The, ideology, was, supported, by, a, large, ...","[Adolf Hitler, Germany, 1933, Nazism, Germany,...","[Germany, Germany]"
41,"(The, Nazi, Party, in, Germany, was, dedicated...","[The Nazi Party, Germany, German, German, Cent...","[Germany, Germany]"
42,"(Antisemitism, during, the, Great, Depression,...","[the Great Depression, Jews, Austria, Austria,...","[Austria, Austria, Germany]"
45,"(Almost, all, of, the, new, democracies, in, t...","[Eastern Europe, Spain, Francisco Franco, the ...",[Spain]
50,"(The, signing, of, the, Molotov, –, Ribbentrop...","[Moscow, 23 August 1939Soon, Czechoslovakia, B...","[France, Poland]"
51,"(World, War, II, officially, began, on, 1, Sep...","[World War II, 1 September 1939, Hitler, Blitz...",[Poland]
52,"(Britain, and, France, ,, much, to, Hitler, 's...","[Britain, France, Hitler, Germany, Poland]","[France, Germany, Poland]"
53,"(Sixteen, days, later, ,, Poland, was, attacke...","[Sixteen days later, Poland, East, Soviet Unio...",[Poland]
57,"(This, change, smashed, any, expectations, tha...","[the Second World War, Hitler, Poland, the Sov...","[Poland, Germany]"
58,"(This, treaty, gave, Stalin, free, rein, to, t...","[Stalin, Baltic, Estonia, Latvia, Lithuania, E...","[Estonia, Latvia, Lithuania, Finland]"
59,"(This, action, would, later, cause, the, Finns...","[Finns, Germany, the Soviet Union, 1941.[44]Bl...","[Germany, Poland]"
60,"(This, changed, when, Hitler, occupied, Denmar...","[Hitler, Denmark, Norway, 9 April 1940]","[Denmark, Norway]"
61,"(Norway, was, strategically, important, becaus...","[Norway, Swedish, Nazi]",[Norway]
62,"(Norway, held, on, for, a, few, crucial, weeks...","[Norway, a few crucial weeks, Denmark, only si...","[Norway, Denmark, Sweden, Germany]"

### Create a Relationships Dataframe

In [72]:


# window size = 5 : this defines how many sentences will be looked at simultaneously 
relationships = [] # create an empty list

for i in range(df_sentences_filtered.index[-1]):
    end_i = min(i+5, df_sentences_filtered.index[-1])
    country_list = sum((df_sentences_filtered.loc[i: end_i].country_entities), [])
    
    # Remove duplicated characters that are next to each other
    country_unique = [country_list[i] for i in range(len(country_list)) 
                   if (i==0) or country_list[i] != country_list[i-1]]
    
    if len(country_unique) > 1:
        for idx, a in enumerate(country_unique[:-1]):
            b = country_unique[idx + 1]
            relationships.append({"source": a, "target": b})

In [73]:
df_relationships = pd.DataFrame(relationships)

In [74]:
df_relationships

      source     target
0     France     Russia
1     France     Russia
2     Russia    Germany
3    Germany     Russia
4     France     Russia
..       ...        ...
651    India  Singapore
652    India  Singapore
653    India  Singapore
654    India  Singapore
655    India  Singapore

[656 rows x 2 columns]

In [75]:
# Sort the cases with a->b and b->a

df_relationships = pd.DataFrame(np.sort(df_relationships.values, axis = 1), columns = df_relationships.columns)
df_relationships.head(5)

    source  target
0   France  Russia
1   France  Russia
2  Germany  Russia
3  Germany  Russia
4   France  Russia

### 9. Export to csv file

In [77]:
# Export dataframe to csv file

df_relationships.to_csv('/Users/andymiller/20th-Century/country_relationships.csv')